export const SET_AVAILABLE_EXERCISES = 'SET_AVAILABLE_EXERCISES';
export const SET_FINISHED_EXERCISES = 'SET_FINISHED_EXERCISES';
export const START_TRAINING = 'START_TRAINING';
export const STOP_TRAINING = 'STOP_TRAINNG';
